telegram_key: 7805646492:AAEfzYJXfaeS9giXfPC1Dwy9efVBHFrGIdA
camera_input:
  resolution: 1920x1080
  fps: 25
  clip:
    segment_size_sec: 5
    segments: 8
    timer_before_clip_sec: 15
    cooldown_sec: 20000
    disk_full_buffer_gb: 4
motion_listener:
  sensitivity_inverse: 50
  threshold_sum_kilo: 500
  frame_delay_millisec: 100
  trigger_duration: 5
gui_stream_output:
  resolution: 1280x720
  bit_rate: 100k
  fps: 2
internet_stream_output:
  url: https://zerocam.stegi56.com/stream1/
  username: zerocamuser
  password: zerocam
  resolution: 1920x1080
  bit_rate: 800k
  fps: 15
g_cloud:
  limit_gb: 14
  backup_scheduler_timeout_sec: 90
hotspot_networks:
  - 5G COVID-19 tower
