[package]
name = "TokenGenerator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
google-drive3 = "6.0"
yup-oauth2 = "12.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"

